# Generated by Django 5.1.4 on 2025-02-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_messagefromemployee_messagefromuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagefromemployee',
            name='account',
        ),
        migrations.RemoveField(
            model_name='messagefromuser',
            name='account',
        ),
        migrations.AddField(
            model_name='messagefromemployee',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='messagefromemployee',
            name='user_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='messagefromuser',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='messagefromuser',
            name='user_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
