# Generated by Django 5.1.4 on 2025-02-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_messagefromemployee_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagefromemployee',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='messagefromemployee',
            name='bank',
        ),
    ]
