# Generated by Django 5.1.4 on 2025-02-13 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_redem'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redem',
            name='bank',
        ),
        migrations.AddField(
            model_name='check',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.bank'),
        ),
    ]
