# Generated by Django 5.1.4 on 2025-02-14 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_account_balance_alter_account_bank'),
        ('bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='check',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recive_check', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='check',
            name='uniq_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
