# Generated by Django 5.1.4 on 2025-02-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagefromuser',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='messagefromuser',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='messagefromuser',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='MessageFromEmployee',
        ),
        migrations.DeleteModel(
            name='MessageFromUser',
        ),
    ]
