# Generated by Django 5.1.4 on 2025-02-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_egn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('employee', 'Служител'), ('third person', 'Трето лице')], default='client', max_length=20),
        ),
    ]
