# Generated by Django 5.1.4 on 2025-02-15 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('users', '0002_remove_messagefromuser_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createemployee',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='createemployee',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.employee'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
