# Generated by Django 5.1.4 on 2025-02-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_createemployee_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, default='Клиент', max_length=20),
        ),
    ]
