# Generated by Django 5.1.4 on 2025-02-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_number',
            field=models.IntegerField(default=0),
        ),
    ]
