# Generated by Django 5.1.4 on 2025-02-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_account_balance_alter_account_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bank_name', models.CharField(max_length=100)),
                ('new_bank_name', models.CharField(max_length=100)),
                ('user_number', models.IntegerField()),
            ],
        ),
    ]
